// Single-shot, NON-agentic generator for API providers (OpenAI, a bare
// Anthropic key, or any other bench.config.json "providers" entry).
//
// IMPORTANT — comparability caveat: this adapter measures "model + a fixed
// context bundle, one completion" — it never reads a file, never sees a
// compiler error, and gets exactly one turn. That is a fundamentally
// different task than the claude-code adapter's multi-turn, tool-using,
// explore-then-edit loop. Cells generated by this adapter are NOT comparable
// to claude-code cells on turns/duration/"agentic capability" — only on the
// mechanical/judgment *output* scores. The report keeps them visually
// separate because the qualified model string (e.g. "openai:gpt-5.2") is
// baked into CellSpec.model, which cellKey/columns/baselines all key off of.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import type { AgentAdapter, AgentGenerateRequest, AgentGenerateResult } from '../types.ts';
import { loadBenchConfig } from '../config.ts';
import { chatComplete, resolveProvider, type ResolvedProvider } from '../providers/client.ts';
import { estimateApiCostUsd } from '../providers/pricing.ts';
import { UsageLimitError } from './errors.ts';

/** Total budget for docs/ content folded into the prompt. */
const MAX_DOCS_BYTES = 40_000;
/** Never shrink a single doc file below this many characters when truncating. */
const MIN_KEEP_PER_FILE = 500;
const TRUNCATION_MARK = '\n[...truncated to fit context budget...]';

const ROOT_CONTEXT_FILES = ['CLAUDE.md', 'AGENTS.md', 'DESIGN.md'];

const FILES_JSON_SCHEMA = {
  name: 'generated_files',
  schema: {
    type: 'object',
    properties: {
      files: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            path: { type: 'string', description: 'Path relative to the workspace root, must be under src/.' },
            content: { type: 'string' },
          },
          required: ['path', 'content'],
          additionalProperties: false,
        },
      },
    },
    required: ['files'],
    additionalProperties: false,
  },
} as const;

// ---------------------------------------------------------------------------
// Context bundle
// ---------------------------------------------------------------------------

interface DocFile {
  relPath: string;
  content: string;
  size: number;
}

function walkFiles(dir: string, root: string, out: DocFile[]): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      walkFiles(p, root, out);
    } else if (entry.isFile()) {
      const content = readFileSync(p, 'utf8');
      out.push({ relPath: relative(root, p), content, size: content.length });
    }
  }
}

/**
 * Collects docs/ content up to MAX_DOCS_BYTES. When the total exceeds budget,
 * shrinks the LARGEST files first (down to MIN_KEEP_PER_FILE), so a benchmark
 * workspace with many small reference docs plus one huge one keeps breadth
 * (all files present) rather than the biggest file eating the whole budget
 * and starving every other doc.
 */
function collectDocs(workspaceDir: string): { text: string; truncatedFiles: string[] } {
  const docsDir = join(workspaceDir, 'docs');
  const files: DocFile[] = [];
  if (existsSync(docsDir)) walkFiles(docsDir, workspaceDir, files);
  if (files.length === 0) return { text: '', truncatedFiles: [] };

  const totalSize = files.reduce((sum, f) => sum + f.size, 0);
  const truncatedFiles: string[] = [];

  if (totalSize > MAX_DOCS_BYTES) {
    let overage = totalSize - MAX_DOCS_BYTES;
    const bySizeDesc = [...files].sort((a, b) => b.size - a.size);
    for (const f of bySizeDesc) {
      if (overage <= 0) break;
      const cut = Math.min(overage, Math.max(0, f.size - MIN_KEEP_PER_FILE));
      if (cut <= 0) continue;
      f.content = f.content.slice(0, f.size - cut) + TRUNCATION_MARK;
      f.size -= cut;
      overage -= cut;
      truncatedFiles.push(f.relPath);
    }
  }

  const text = files.map((f) => `### ${f.relPath}\n\n${f.content}`).join('\n\n---\n\n');
  return { text, truncatedFiles };
}

function buildContextBundle(workspaceDir: string): string {
  const parts: string[] = [];

  const readmePath = join(workspaceDir, 'README.md');
  if (existsSync(readmePath)) {
    parts.push(`## Workspace README.md\n\n${readFileSync(readmePath, 'utf8')}`);
  }

  for (const name of ROOT_CONTEXT_FILES) {
    const p = join(workspaceDir, name);
    if (existsSync(p)) parts.push(`## ${name}\n\n${readFileSync(p, 'utf8')}`);
  }

  const { text: docsText, truncatedFiles } = collectDocs(workspaceDir);
  if (docsText) {
    parts.push(`## docs/\n\n${docsText}`);
    if (truncatedFiles.length) {
      parts.push(
        `(context note: the following docs/ files were shortened to fit the ~${Math.round(MAX_DOCS_BYTES / 1000)}KB docs budget: ${truncatedFiles.join(', ')})`,
      );
    }
  }

  const taskIndexPath = join(workspaceDir, 'src', 'task', 'index.tsx');
  if (existsSync(taskIndexPath)) {
    parts.push(`## Current src/task/index.tsx\n\n\`\`\`tsx\n${readFileSync(taskIndexPath, 'utf8')}\n\`\`\``);
  }

  return parts.join('\n\n---\n\n');
}

function buildSystemPrompt(appendSystemPrompt: string | undefined): string {
  const base =
    appendSystemPrompt ??
    'Implement the requested feature in this workspace (a Vite React TypeScript app). ' +
      'Put your implementation in src/task/ (see README.md). Do not modify files outside src/.';
  return (
    `${base} This is a single-shot generation: you cannot browse the filesystem, run tools, or see ` +
    'compiler feedback beyond the context bundle given to you in the user message. ' +
    'Return ONLY JSON matching the schema: {files:[{path,content}]} — paths relative to the workspace root, under src/ only.'
  );
}

// ---------------------------------------------------------------------------
// Path safety
// ---------------------------------------------------------------------------

/** Rejects paths that escape the workspace root or land outside src/. */
function isSafeWorkspacePath(workspaceDir: string, rawPath: string): boolean {
  if (!rawPath || rawPath.includes('\0')) return false;
  const root = resolve(workspaceDir);
  const abs = resolve(root, rawPath);
  const withinRoot = abs === root || abs.startsWith(root + sep);
  if (!withinRoot) return false;
  const fromRoot = relative(root, abs);
  return fromRoot === 'src' || fromRoot.startsWith(`src${sep}`);
}

function extractFiles(json: unknown): Array<{ path: string; content: string }> {
  if (!json || typeof json !== 'object') return [];
  const files = (json as Record<string, unknown>).files;
  if (!Array.isArray(files)) return [];
  const out: Array<{ path: string; content: string }> = [];
  for (const f of files) {
    if (f && typeof f === 'object') {
      const ff = f as Record<string, unknown>;
      if (typeof ff.path === 'string' && typeof ff.content === 'string') {
        out.push({ path: ff.path, content: ff.content });
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

/**
 * Does the actual work once a provider is already resolved. Split out from
 * the AgentAdapter.generate() entry point purely for testability: tests can
 * hand this a ResolvedProvider that points at a local node:http mock server
 * without touching the real bench.config.json or any provider env var.
 *
 * Completion budget is the model's advertised max_tokens from the pricing
 * catalog (see resolveMaxTokens). Do not pass a smaller maxTokens — thinking
 * models spend a large share of that budget on reasoning before they emit
 * the file JSON, and a 32k cap truncated Gemini mid-string.
 */
export async function generateWithResolvedProvider(
  req: AgentGenerateRequest,
  provider: ResolvedProvider,
  startedAt: number = Date.now(),
): Promise<AgentGenerateResult> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), req.timeoutMs);

  try {
    const systemPrompt = buildSystemPrompt(req.appendSystemPrompt);
    const contextBundle = buildContextBundle(req.workspaceDir);
    const userPrompt = [req.prompt, '', '## Workspace context', contextBundle].join('\n');

    const result = await chatComplete(provider, {
      system: systemPrompt,
      user: userPrompt,
      model: req.model,
      jsonSchema: FILES_JSON_SCHEMA,
      signal: controller.signal,
    });

    const files = extractFiles(result.json);
    const written: string[] = [];
    const rejected: string[] = [];
    for (const f of files) {
      if (isSafeWorkspacePath(req.workspaceDir, f.path)) {
        const abs = join(req.workspaceDir, f.path);
        mkdirSync(dirname(abs), { recursive: true });
        writeFileSync(abs, f.content, 'utf8');
        written.push(f.path);
      } else {
        rejected.push(f.path);
      }
    }

    writeFileSync(
      req.transcriptPath,
      JSON.stringify(
        {
          provider: req.provider,
          model: req.model,
          written,
          rejected,
          usage: result.usage,
          raw: result.text.slice(0, 20_000),
        },
        null,
        2,
      ),
    );

    const resultText =
      `wrote ${written.length} file(s)` +
      (rejected.length ? `; rejected ${rejected.length} unsafe path(s): ${rejected.join(', ')}` : '');

    const usage = result.usage;
    const costUsd = usage
      ? estimateApiCostUsd(req.model, usage)
      : undefined;

    return {
      ok: true,
      timedOut: false,
      exitCode: 0,
      durationMs: Date.now() - startedAt,
      numTurns: 1,
      inputTokens: usage?.inputTokens,
      outputTokens: usage?.outputTokens,
      costUsd,
      transcriptPath: req.transcriptPath,
      resultText,
    };
  } catch (err) {
    const timedOut = controller.signal.aborted && !(err instanceof UsageLimitError);
    if (err instanceof UsageLimitError) {
      writeFileSync(req.transcriptPath, `usage-limit: ${err.message}`);
      return {
        ok: false,
        timedOut: false,
        exitCode: null,
        durationMs: Date.now() - startedAt,
        transcriptPath: req.transcriptPath,
        resultText: err.message,
        errorKind: 'usage-limit',
      };
    }
    const message = err instanceof Error ? err.message : String(err);
    writeFileSync(req.transcriptPath, message);
    return {
      ok: false,
      timedOut,
      exitCode: null,
      durationMs: Date.now() - startedAt,
      transcriptPath: req.transcriptPath,
      resultText: message,
      errorKind: 'other',
    };
  } finally {
    clearTimeout(timer);
  }
}

export const apiOneshotAdapter: AgentAdapter = {
  id: 'api-oneshot',

  async detect() {
    // Real availability depends on which provider's apiKeyEnv is set, which
    // is per-cell (req.provider) rather than a single fixed binary — checked
    // at generate() time and surfaced via `doctor`'s providers block instead.
    return { ok: true, version: 'api-oneshot (single-shot API adapter, no CLI)' };
  },

  async generate(req: AgentGenerateRequest): Promise<AgentGenerateResult> {
    const startedAt = Date.now();
    if (!req.provider) {
      const msg = 'api-oneshot adapter requires req.provider (a qualified "provider:model" was expected)';
      writeFileSync(req.transcriptPath, msg);
      return {
        ok: false,
        timedOut: false,
        exitCode: null,
        durationMs: Date.now() - startedAt,
        transcriptPath: req.transcriptPath,
        resultText: msg,
        errorKind: 'other',
      };
    }

    let provider: ResolvedProvider;
    try {
      provider = resolveProvider(req.provider, loadBenchConfig());
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      writeFileSync(req.transcriptPath, message);
      return {
        ok: false,
        timedOut: false,
        exitCode: null,
        durationMs: Date.now() - startedAt,
        transcriptPath: req.transcriptPath,
        resultText: message,
        errorKind: 'other',
      };
    }

    return generateWithResolvedProvider(req, provider, startedAt);
  },
};
